# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  test-code-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test code
        uses: ghcr.io/simple-home/simplehome-container-dev:master
        run: |
          composer install --no-interaction --optimize-autoloader --no-suggest --no-scripts --dev
          ./vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
          ./vendor/bin/phpcs -s -p -n --colors --standard=PHPCompatibility --runtime-set testVersion 7.4 app/
          ./vendor/bin/phpunit
